"""Initial migration.

Revision ID: 4d7782c038de
Revises: 
Create Date: 2024-05-30 12:54:49.075816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7782c038de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('screenshot', sa.String(length=256), nullable=True),
    sa.Column('active_window', sa.String(length=256), nullable=True),
    sa.Column('keyboard_events', sa.Integer(), nullable=True),
    sa.Column('mouse_events', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_timestamp'), ['timestamp'], unique=False)

    op.create_table('work_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_session_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_session_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_work_session_end_time'))

    op.drop_table('work_session')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_timestamp'))

    op.drop_table('activity')
    op.drop_table('user')
    # ### end Alembic commands ###
